### ISSUE TITLE
Mac OS installation

### ISSUE THREAD

**Issue by hgmnz** [tomz/libsvm-ruby-swig#1]
Would it be possible to get a listing of requirements and/or detailed usage of this interface?

I am trying to install on Mac OS. I installed libsvm via macports, and installation seems to be fine.
However, when I require 'svm', I get the following error and stack trace:

```
  LoadError: dlopen(/Library/Ruby/Gems/1.8/gems/tomz-libsvm-ruby-swig-0.3.3/ext/libsvm.bundle, 9): Symbol not found: __ZTVN10__cxxabiv117__class_type_infoE
    Referenced from: /Library/Ruby/Gems/1.8/gems/tomz-libsvm-ruby-swig-0.3.3/ext/libsvm.bundle
    Expected in: dynamic lookup
   - /Library/Ruby/Gems/1.8/gems/tomz-libsvm-ruby-swig-0.3.3/ext/libsvm.bundle
    from /Library/Ruby/Gems/1.8/gems/tomz-libsvm-ruby-swig-0.3.3/ext/libsvm.bundle
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/tomz-libsvm-ruby-swig-0.3.3/lib/svm.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from (irb):1
```

Any help or ideas around this would be most appreciated!

Thanks,
-Harold

**Comment by hgmnz** [comment]
Could this be related to my gcc version? 

I am on 4.0.1:

```
$ gcc --version
i686-apple-darwin9-gcc-4.0.1 (GCC) 4.0.1 (Apple Inc. build 5493)
```

**Comment by drnic** [comment]
I had the similar issue. Installed via macports (2.9) and with gcc 4.2.1.

<pre>
> require 'svm'
LoadError: dlopen(/Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.bundle, 9): Symbol not found: __ZTVN10__cxxabiv117__class_type_infoE
  Referenced from: /Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.bundle
  Expected in: flat namespace
 in /Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.bundle - /Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.bundle
    from /Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.bundle
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/libsvm-ruby-swig-0.4.0/lib/svm.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from (irb):1
</pre>

**Comment by martennilsson** [comment]
Same here, any pointers?

**Comment by occamsRZR** [comment]
If anyone is still having the same problems...
I am running OSX.5.8.  When trying to do the 'gem install ...' using ruby 1.8.6 it would say the gem was installed but when I used " require 'svm' " it would give me the exact same error message all of you are getting.
I followed hivelogic's guide to upgrading ruby: http://hivelogic.com/articles/ruby-rails-leopard.
After upgrading to 1.9.2p0, I reinstalled the gem using the default 'gem install...' command.  It successfully installed the gem as well as the documentation.  A quick check with irb (require 'svm') FINALLY returned 'true'.  

Sorry for the formatting, just made a new github account just to share this info.
