### ISSUE TITLE
Problem.new causes TypeError: in method 'double_setitem'

### ISSUE THREAD

**Issue by mrgordon** [tomz/libsvm-ruby-swig#4]
Any thoughts on the following error that is occurring in the Problem `initialize` method? It works on my local OS X box but is failing on an Ubuntu 10.04 box.

`1.9.3p125 :028 > Problem.new( [1, 1, 0] , [[0], [0], [1]])
TypeError: in method 'double_setitem', argument 1 of type 'double *'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/tomz-libsvm-ruby-swig-0.3.3/lib/svm.rb:145:in `double_setitem'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/tomz-libsvm-ruby-swig-0.3.3/lib/svm.rb:145:in `block in initialize'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/tomz-libsvm-ruby-swig-0.3.3/lib/svm.rb:144:in `each'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/tomz-libsvm-ruby-swig-0.3.3/lib/svm.rb:144:in `initialize'
    from (irb):28:in `new'
    from (irb):28
    from /workspace/vendor/bundle/ruby/1.9.1/gems/railties-3.2.1/lib/rails/commands/console.rb:47:in `start'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/railties-3.2.1/lib/rails/commands/console.rb:8:in `start'
    from /workspace/vendor/bundle/ruby/1.9.1/gems/railties-3.2.1/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'`

**Comment by mrgordon** [comment]
I have it failing on two boxes and passing on one, all running Ubuntu 10.04.3 LTS. Trying to isolate what could be causing the TypeError above on the two boxes. Any ideas are much appreciated and I will share what I find.
